// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IFleetMergeSystem
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IFleetMergeSystem {
  function mergeFleets(bytes32[] calldata fleets) external;
}
