// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

import { PositionData } from "codegen/index.sol";

/**
 * @title IMoveBuildingSystem
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IMoveBuildingSystem {
  function moveBuilding(PositionData memory fromCoord, PositionData memory toCoord) external;
}
