// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IS_BattleEncryptionResolveSystem
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IS_BattleEncryptionResolveSystem {
  function resolveBattleEncryption(
    bytes32 battleId,
    bytes32 targetSpaceRock,
    bytes32 aggressorEntity,
    bytes32 aggressorDecryptionUnitPrototype,
    uint256 aggressorDecryption
  ) external;
}
