// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

import { PositionData } from "codegen/index.sol";

/**
 * @title IS_CreateSecondaryAsteroidSystem
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IS_CreateSecondaryAsteroidSystem {
  function createSecondaryAsteroid(PositionData memory positionData) external returns (bytes32);
}
