// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

import { EUnit } from "src/Types.sol";

/**
 * @title ITrainUnitsSystem
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface ITrainUnitsSystem {
  function trainUnits(bytes32 buildingEntity, EUnit unit, uint256 count) external;

  function trainUnits(bytes32 buildingEntity, bytes32 unitPrototype, uint256 count) external;
}
