// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { EBuilding } from "src/Types.sol";
import { PositionData } from "codegen/index.sol";

/**
 * @title IBuildSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IBuildSystem {
  function Pri_11__build(EBuilding buildingType, PositionData memory coord) external returns (bytes32 buildingEntity);
}
