// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IClaimPrimodiumSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IClaimPrimodiumSystem {
  function Pri_11__claimPrimodium(bytes32 asteroidEntity) external;

  function Pri_11__claimShardAsteroidPoints(bytes32 asteroidEntity) external;
}
