// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { EObjectives } from "src/Types.sol";

/**
 * @title IClaimObjectiveSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IClaimObjectiveSystem {
  function Pri_11__claimObjective(bytes32 asteroidEntity, EObjectives objective) external;
}
