// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IClaimWormholeSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IClaimWormholeSystem {
  function Pri_11__wormholeDeposit(bytes32 wormholeBaseEntity, uint256 count) external;
}
