// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IColonySystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IColonySystem {
  function Pri_11__payForMaxColonySlots(
    bytes32 shipyardEntity,
    uint256[] calldata paymentAmounts
  ) external returns (bool);

  function Pri_11__changeHome(bytes32 asteroidEntity) external;
}
