// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IFleetClearSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IFleetClearSystem {
  function Pri_11__abandonFleet(bytes32 fleetEntity) external;

  function Pri_11__clearFleet(bytes32 fleetEntity) external;

  function Pri_11__clearUnitsAndResourcesFromFleet(
    bytes32 fleetEntity,
    uint256[] calldata unitCounts,
    uint256[] calldata resourceCounts
  ) external;

  function Pri_11__clearUnits(bytes32 fleetEntity, uint256[] calldata unitCounts) external;

  function Pri_11__clearResources(bytes32 fleetEntity, uint256[] calldata resourceCounts) external;
}
