// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IS_BattleEncryptionResolveSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IS_BattleEncryptionResolveSystem {
  function Pri_11__resolveBattleEncryption(
    bytes32 battleEntity,
    bytes32 targetAsteroid,
    bytes32 aggressorEntity
  ) external;
}
