// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IS_BattleRaidResolveSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IS_BattleRaidResolveSystem {
  function Pri_11__battleRaidResolve(bytes32 battleEntity, bytes32 raider, bytes32 target) external;
}
