// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IS_BattleApplyDamageSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IS_BattleApplyDamageSystem {
  function Pri_11__applyDamage(
    bytes32 battleEntity,
    bytes32 attackingPlayer,
    bytes32 defender,
    uint256 damage
  ) external returns (uint256);
}
