// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { PositionData } from "codegen/index.sol";

/**
 * @title IS_CreateSecondaryAsteroidSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IS_CreateSecondaryAsteroidSystem {
  function Pri_11__createSecondaryAsteroid(PositionData memory positionData) external returns (bytes32);
}
