// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IS_ProductionRateSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IS_ProductionRateSystem {
  function Pri_11__upgradeProductionRate(bytes32 buildingEntity, uint256 level) external;

  function Pri_11__toggleProductionRate(bytes32 buildingEntity) external;

  function Pri_11__clearProductionRate(bytes32 buildingEntity) external;
}
