// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IS_RewardsSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IS_RewardsSystem {
  function Pri_11__receiveRewards(bytes32 asteroidEntity, bytes32 objectivePrototype) external;
}
