// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IS_StorageSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IS_StorageSystem {
  function Pri_11__increaseMaxStorage(bytes32 buildingEntity, uint256 level) external;

  function Pri_11__clearMaxStorageIncrease(bytes32 buildingEntity) external;

  function Pri_11__toggleMaxStorage(bytes32 buildingEntity) external;
}
