// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title ITransferTwoWaySystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface ITransferTwoWaySystem {
  function Pri_11__transferUnitsTwoWay(bytes32 leftEntity, bytes32 rightEntity, int256[] calldata unitCounts) external;

  function Pri_11__transferResourcesTwoWay(
    bytes32 leftEntity,
    bytes32 rightEntity,
    int256[] calldata resourceCounts
  ) external;

  function Pri_11__transferUnitsAndResourcesTwoWay(
    bytes32 leftEntity,
    bytes32 rightEntity,
    int256[] calldata unitCounts,
    int256[] calldata resourceCounts
  ) external;
}
