// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { EUnit } from "src/Types.sol";

/**
 * @title IUpgradeUnitSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IUpgradeUnitSystem {
  function Pri_11__upgradeUnit(bytes32 asteroidEntity, EUnit unit) external;
}
