// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

import { AllianceMembersSet } from "../libraries/AllianceMembersSet.sol";
import { ColoniesMap } from "../libraries/ColoniesMap.sol";
import { LibAlliance } from "../libraries/LibAlliance.sol";
import { LibAsteroid } from "../libraries/LibAsteroid.sol";
import { LibBuilding } from "../libraries/LibBuilding.sol";
import { LibCombatAttributes } from "../libraries/LibCombatAttributes.sol";
import { LibEncode } from "../libraries/LibEncode.sol";
import { LibMarketplace } from "../libraries/LibMarketplace.sol";
import { LibMath } from "../libraries/LibMath.sol";
import { LibObjectives } from "../libraries/LibObjectives.sol";
import { LibPirate } from "../libraries/LibPirate.sol";
import { LibProduction } from "../libraries/LibProduction.sol";
import { LibReduceProductionRate } from "../libraries/LibReduceProductionRate.sol";
import { LibResource } from "../libraries/LibResource.sol";
import { LibReward } from "../libraries/LibReward.sol";
import { LibScore } from "../libraries/LibScore.sol";
import { LibStorage } from "../libraries/LibStorage.sol";
import { LibUnit } from "../libraries/LibUnit.sol";
import { UnitFactorySet } from "../libraries/UnitFactorySet.sol";
import { UnitProductionQueue } from "../libraries/UnitProductionQueue.sol";
import { UtilityMap } from "../libraries/UtilityMap.sol";
