// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

// Import schema type
import { SchemaType } from "@latticexyz/schema-type/src/solidity/SchemaType.sol";

// Import store internals
import { IStore } from "@latticexyz/store/src/IStore.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";
import { StoreCore } from "@latticexyz/store/src/StoreCore.sol";
import { Bytes } from "@latticexyz/store/src/Bytes.sol";
import { Memory } from "@latticexyz/store/src/Memory.sol";
import { SliceLib } from "@latticexyz/store/src/Slice.sol";
import { EncodeArray } from "@latticexyz/store/src/tightcoder/EncodeArray.sol";
import { FieldLayout, FieldLayoutLib } from "@latticexyz/store/src/FieldLayout.sol";
import { Schema, SchemaLib } from "@latticexyz/store/src/Schema.sol";
import { PackedCounter, PackedCounterLib } from "@latticexyz/store/src/PackedCounter.sol";
import { ResourceId } from "@latticexyz/store/src/ResourceId.sol";
import { RESOURCE_TABLE, RESOURCE_OFFCHAIN_TABLE } from "@latticexyz/store/src/storeResourceTypes.sol";

ResourceId constant _tableId = ResourceId.wrap(
  bytes32(abi.encodePacked(RESOURCE_TABLE, bytes14(""), bytes16("P_Unit")))
);
ResourceId constant P_UnitTableId = _tableId;

FieldLayout constant _fieldLayout = FieldLayout.wrap(
  0x00e0070020202020202020000000000000000000000000000000000000000000
);

struct P_UnitData {
  uint256 attack;
  uint256 defense;
  uint256 speed;
  uint256 cargo;
  uint256 trainingTime;
  uint256 hp;
  uint256 decryption;
}

library P_Unit {
  /**
   * @notice Get the table values' field layout.
   * @return _fieldLayout The field layout for the table.
   */
  function getFieldLayout() internal pure returns (FieldLayout) {
    return _fieldLayout;
  }

  /**
   * @notice Get the table's key schema.
   * @return _keySchema The key schema for the table.
   */
  function getKeySchema() internal pure returns (Schema) {
    SchemaType[] memory _keySchema = new SchemaType[](2);
    _keySchema[0] = SchemaType.BYTES32;
    _keySchema[1] = SchemaType.UINT256;

    return SchemaLib.encode(_keySchema);
  }

  /**
   * @notice Get the table's value schema.
   * @return _valueSchema The value schema for the table.
   */
  function getValueSchema() internal pure returns (Schema) {
    SchemaType[] memory _valueSchema = new SchemaType[](7);
    _valueSchema[0] = SchemaType.UINT256;
    _valueSchema[1] = SchemaType.UINT256;
    _valueSchema[2] = SchemaType.UINT256;
    _valueSchema[3] = SchemaType.UINT256;
    _valueSchema[4] = SchemaType.UINT256;
    _valueSchema[5] = SchemaType.UINT256;
    _valueSchema[6] = SchemaType.UINT256;

    return SchemaLib.encode(_valueSchema);
  }

  /**
   * @notice Get the table's key field names.
   * @return keyNames An array of strings with the names of key fields.
   */
  function getKeyNames() internal pure returns (string[] memory keyNames) {
    keyNames = new string[](2);
    keyNames[0] = "entity";
    keyNames[1] = "level";
  }

  /**
   * @notice Get the table's value field names.
   * @return fieldNames An array of strings with the names of value fields.
   */
  function getFieldNames() internal pure returns (string[] memory fieldNames) {
    fieldNames = new string[](7);
    fieldNames[0] = "attack";
    fieldNames[1] = "defense";
    fieldNames[2] = "speed";
    fieldNames[3] = "cargo";
    fieldNames[4] = "trainingTime";
    fieldNames[5] = "hp";
    fieldNames[6] = "decryption";
  }

  /**
   * @notice Register the table with its config.
   */
  function register() internal {
    StoreSwitch.registerTable(_tableId, _fieldLayout, getKeySchema(), getValueSchema(), getKeyNames(), getFieldNames());
  }

  /**
   * @notice Register the table with its config.
   */
  function _register() internal {
    StoreCore.registerTable(_tableId, _fieldLayout, getKeySchema(), getValueSchema(), getKeyNames(), getFieldNames());
  }

  /**
   * @notice Get attack.
   */
  function getAttack(bytes32 entity, uint256 level) internal view returns (uint256 attack) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = entity;
    _keyTuple[1] = bytes32(uint256(level));

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Get attack.
   */
  function _getAttack(bytes32 entity, uint256 level) internal view returns (uint256 attack) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = entity;
    _keyTuple[1] = bytes32(uint256(level));

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Set attack.
   */
  function setAttack(bytes32 entity, uint256 level, uint256 attack) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = entity;
    _keyTuple[1] = bytes32(uint256(level));

    StoreSwitch.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((attack)), _fieldLayout);
  }

  /**
   * @notice Set attack.
   */
  function _setAttack(bytes32 entity, uint256 level, uint256 attack) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = entity;
    _keyTuple[1] = bytes32(uint256(level));

    StoreCore.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((attack)), _fieldLayout);
  }

  /**
   * @notice Get defense.
   */
  function getDefense(bytes32 entity, uint256 level) internal view returns (uint256 defense) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = entity;
    _keyTuple[1] = bytes32(uint256(level));

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 1, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Get defense.
   */
  function _getDefense(bytes32 entity, uint256 level) internal view returns (uint256 defense) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = entity;
    _keyTuple[1] = bytes32(uint256(level));

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 1, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Set defense.
   */
  function setDefense(bytes32 entity, uint256 level, uint256 defense) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = entity;
    _keyTuple[1] = bytes32(uint256(level));

    StoreSwitch.setStaticField(_tableId, _keyTuple, 1, abi.encodePacked((defense)), _fieldLayout);
  }

  /**
   * @notice Set defense.
   */
  function _setDefense(bytes32 entity, uint256 level, uint256 defense) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = entity;
    _keyTuple[1] = bytes32(uint256(level));

    StoreCore.setStaticField(_tableId, _keyTuple, 1, abi.encodePacked((defense)), _fieldLayout);
  }

  /**
   * @notice Get speed.
   */
  function getSpeed(bytes32 entity, uint256 level) internal view returns (uint256 speed) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = entity;
    _keyTuple[1] = bytes32(uint256(level));

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 2, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Get speed.
   */
  function _getSpeed(bytes32 entity, uint256 level) internal view returns (uint256 speed) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = entity;
    _keyTuple[1] = bytes32(uint256(level));

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 2, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Set speed.
   */
  function setSpeed(bytes32 entity, uint256 level, uint256 speed) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = entity;
    _keyTuple[1] = bytes32(uint256(level));

    StoreSwitch.setStaticField(_tableId, _keyTuple, 2, abi.encodePacked((speed)), _fieldLayout);
  }

  /**
   * @notice Set speed.
   */
  function _setSpeed(bytes32 entity, uint256 level, uint256 speed) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = entity;
    _keyTuple[1] = bytes32(uint256(level));

    StoreCore.setStaticField(_tableId, _keyTuple, 2, abi.encodePacked((speed)), _fieldLayout);
  }

  /**
   * @notice Get cargo.
   */
  function getCargo(bytes32 entity, uint256 level) internal view returns (uint256 cargo) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = entity;
    _keyTuple[1] = bytes32(uint256(level));

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 3, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Get cargo.
   */
  function _getCargo(bytes32 entity, uint256 level) internal view returns (uint256 cargo) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = entity;
    _keyTuple[1] = bytes32(uint256(level));

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 3, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Set cargo.
   */
  function setCargo(bytes32 entity, uint256 level, uint256 cargo) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = entity;
    _keyTuple[1] = bytes32(uint256(level));

    StoreSwitch.setStaticField(_tableId, _keyTuple, 3, abi.encodePacked((cargo)), _fieldLayout);
  }

  /**
   * @notice Set cargo.
   */
  function _setCargo(bytes32 entity, uint256 level, uint256 cargo) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = entity;
    _keyTuple[1] = bytes32(uint256(level));

    StoreCore.setStaticField(_tableId, _keyTuple, 3, abi.encodePacked((cargo)), _fieldLayout);
  }

  /**
   * @notice Get trainingTime.
   */
  function getTrainingTime(bytes32 entity, uint256 level) internal view returns (uint256 trainingTime) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = entity;
    _keyTuple[1] = bytes32(uint256(level));

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 4, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Get trainingTime.
   */
  function _getTrainingTime(bytes32 entity, uint256 level) internal view returns (uint256 trainingTime) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = entity;
    _keyTuple[1] = bytes32(uint256(level));

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 4, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Set trainingTime.
   */
  function setTrainingTime(bytes32 entity, uint256 level, uint256 trainingTime) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = entity;
    _keyTuple[1] = bytes32(uint256(level));

    StoreSwitch.setStaticField(_tableId, _keyTuple, 4, abi.encodePacked((trainingTime)), _fieldLayout);
  }

  /**
   * @notice Set trainingTime.
   */
  function _setTrainingTime(bytes32 entity, uint256 level, uint256 trainingTime) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = entity;
    _keyTuple[1] = bytes32(uint256(level));

    StoreCore.setStaticField(_tableId, _keyTuple, 4, abi.encodePacked((trainingTime)), _fieldLayout);
  }

  /**
   * @notice Get hp.
   */
  function getHp(bytes32 entity, uint256 level) internal view returns (uint256 hp) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = entity;
    _keyTuple[1] = bytes32(uint256(level));

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 5, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Get hp.
   */
  function _getHp(bytes32 entity, uint256 level) internal view returns (uint256 hp) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = entity;
    _keyTuple[1] = bytes32(uint256(level));

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 5, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Set hp.
   */
  function setHp(bytes32 entity, uint256 level, uint256 hp) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = entity;
    _keyTuple[1] = bytes32(uint256(level));

    StoreSwitch.setStaticField(_tableId, _keyTuple, 5, abi.encodePacked((hp)), _fieldLayout);
  }

  /**
   * @notice Set hp.
   */
  function _setHp(bytes32 entity, uint256 level, uint256 hp) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = entity;
    _keyTuple[1] = bytes32(uint256(level));

    StoreCore.setStaticField(_tableId, _keyTuple, 5, abi.encodePacked((hp)), _fieldLayout);
  }

  /**
   * @notice Get decryption.
   */
  function getDecryption(bytes32 entity, uint256 level) internal view returns (uint256 decryption) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = entity;
    _keyTuple[1] = bytes32(uint256(level));

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 6, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Get decryption.
   */
  function _getDecryption(bytes32 entity, uint256 level) internal view returns (uint256 decryption) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = entity;
    _keyTuple[1] = bytes32(uint256(level));

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 6, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Set decryption.
   */
  function setDecryption(bytes32 entity, uint256 level, uint256 decryption) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = entity;
    _keyTuple[1] = bytes32(uint256(level));

    StoreSwitch.setStaticField(_tableId, _keyTuple, 6, abi.encodePacked((decryption)), _fieldLayout);
  }

  /**
   * @notice Set decryption.
   */
  function _setDecryption(bytes32 entity, uint256 level, uint256 decryption) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = entity;
    _keyTuple[1] = bytes32(uint256(level));

    StoreCore.setStaticField(_tableId, _keyTuple, 6, abi.encodePacked((decryption)), _fieldLayout);
  }

  /**
   * @notice Get the full data.
   */
  function get(bytes32 entity, uint256 level) internal view returns (P_UnitData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = entity;
    _keyTuple[1] = bytes32(uint256(level));

    (bytes memory _staticData, PackedCounter _encodedLengths, bytes memory _dynamicData) = StoreSwitch.getRecord(
      _tableId,
      _keyTuple,
      _fieldLayout
    );
    return decode(_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Get the full data.
   */
  function _get(bytes32 entity, uint256 level) internal view returns (P_UnitData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = entity;
    _keyTuple[1] = bytes32(uint256(level));

    (bytes memory _staticData, PackedCounter _encodedLengths, bytes memory _dynamicData) = StoreCore.getRecord(
      _tableId,
      _keyTuple,
      _fieldLayout
    );
    return decode(_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using individual values.
   */
  function set(
    bytes32 entity,
    uint256 level,
    uint256 attack,
    uint256 defense,
    uint256 speed,
    uint256 cargo,
    uint256 trainingTime,
    uint256 hp,
    uint256 decryption
  ) internal {
    bytes memory _staticData = encodeStatic(attack, defense, speed, cargo, trainingTime, hp, decryption);

    PackedCounter _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = entity;
    _keyTuple[1] = bytes32(uint256(level));

    StoreSwitch.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using individual values.
   */
  function _set(
    bytes32 entity,
    uint256 level,
    uint256 attack,
    uint256 defense,
    uint256 speed,
    uint256 cargo,
    uint256 trainingTime,
    uint256 hp,
    uint256 decryption
  ) internal {
    bytes memory _staticData = encodeStatic(attack, defense, speed, cargo, trainingTime, hp, decryption);

    PackedCounter _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = entity;
    _keyTuple[1] = bytes32(uint256(level));

    StoreCore.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData, _fieldLayout);
  }

  /**
   * @notice Set the full data using the data struct.
   */
  function set(bytes32 entity, uint256 level, P_UnitData memory _table) internal {
    bytes memory _staticData = encodeStatic(
      _table.attack,
      _table.defense,
      _table.speed,
      _table.cargo,
      _table.trainingTime,
      _table.hp,
      _table.decryption
    );

    PackedCounter _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = entity;
    _keyTuple[1] = bytes32(uint256(level));

    StoreSwitch.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using the data struct.
   */
  function _set(bytes32 entity, uint256 level, P_UnitData memory _table) internal {
    bytes memory _staticData = encodeStatic(
      _table.attack,
      _table.defense,
      _table.speed,
      _table.cargo,
      _table.trainingTime,
      _table.hp,
      _table.decryption
    );

    PackedCounter _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = entity;
    _keyTuple[1] = bytes32(uint256(level));

    StoreCore.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData, _fieldLayout);
  }

  /**
   * @notice Decode the tightly packed blob of static data using this table's field layout.
   */
  function decodeStatic(
    bytes memory _blob
  )
    internal
    pure
    returns (
      uint256 attack,
      uint256 defense,
      uint256 speed,
      uint256 cargo,
      uint256 trainingTime,
      uint256 hp,
      uint256 decryption
    )
  {
    attack = (uint256(Bytes.slice32(_blob, 0)));

    defense = (uint256(Bytes.slice32(_blob, 32)));

    speed = (uint256(Bytes.slice32(_blob, 64)));

    cargo = (uint256(Bytes.slice32(_blob, 96)));

    trainingTime = (uint256(Bytes.slice32(_blob, 128)));

    hp = (uint256(Bytes.slice32(_blob, 160)));

    decryption = (uint256(Bytes.slice32(_blob, 192)));
  }

  /**
   * @notice Decode the tightly packed blobs using this table's field layout.
   * @param _staticData Tightly packed static fields.
   *
   *
   */
  function decode(
    bytes memory _staticData,
    PackedCounter,
    bytes memory
  ) internal pure returns (P_UnitData memory _table) {
    (
      _table.attack,
      _table.defense,
      _table.speed,
      _table.cargo,
      _table.trainingTime,
      _table.hp,
      _table.decryption
    ) = decodeStatic(_staticData);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function deleteRecord(bytes32 entity, uint256 level) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = entity;
    _keyTuple[1] = bytes32(uint256(level));

    StoreSwitch.deleteRecord(_tableId, _keyTuple);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function _deleteRecord(bytes32 entity, uint256 level) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = entity;
    _keyTuple[1] = bytes32(uint256(level));

    StoreCore.deleteRecord(_tableId, _keyTuple, _fieldLayout);
  }

  /**
   * @notice Tightly pack static (fixed length) data using this table's schema.
   * @return The static data, encoded into a sequence of bytes.
   */
  function encodeStatic(
    uint256 attack,
    uint256 defense,
    uint256 speed,
    uint256 cargo,
    uint256 trainingTime,
    uint256 hp,
    uint256 decryption
  ) internal pure returns (bytes memory) {
    return abi.encodePacked(attack, defense, speed, cargo, trainingTime, hp, decryption);
  }

  /**
   * @notice Encode all of a record's fields.
   * @return The static (fixed length) data, encoded into a sequence of bytes.
   * @return The lengths of the dynamic fields (packed into a single bytes32 value).
   * @return The dyanmic (variable length) data, encoded into a sequence of bytes.
   */
  function encode(
    uint256 attack,
    uint256 defense,
    uint256 speed,
    uint256 cargo,
    uint256 trainingTime,
    uint256 hp,
    uint256 decryption
  ) internal pure returns (bytes memory, PackedCounter, bytes memory) {
    bytes memory _staticData = encodeStatic(attack, defense, speed, cargo, trainingTime, hp, decryption);

    PackedCounter _encodedLengths;
    bytes memory _dynamicData;

    return (_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Encode keys as a bytes32 array using this table's field layout.
   */
  function encodeKeyTuple(bytes32 entity, uint256 level) internal pure returns (bytes32[] memory) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = entity;
    _keyTuple[1] = bytes32(uint256(level));

    return _keyTuple;
  }
}
