// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

import { EAllianceInviteMode, EAllianceRole } from "src/Types.sol";

/**
 * @title IAllianceSystem
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IAllianceSystem {
  function join(bytes32 alliance) external;

  function create(bytes32 name, EAllianceInviteMode allianceInviteMode) external returns (bytes32 allianceEntity);

  function leave() external;

  function invite(bytes32 target) external;

  function revokeInvite(bytes32 target) external;

  function declineInvite(bytes32 inviter) external;

  function kick(bytes32 target) external;

  function grantRole(bytes32 target, EAllianceRole role) external;

  function requestToJoin(bytes32 alliance) external;

  function rejectRequestToJoin(bytes32 rejectee) external;

  function acceptRequestToJoin(bytes32 accepted) external;
}
