// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IFleetRecallSystem
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IFleetRecallSystem {
  function recallFleet(bytes32 fleetId) external;
}
