// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IFleetStanceSystem
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IFleetStanceSystem {
  function clearFleetStance(bytes32 fleetId) external;

  function setFleetStance(bytes32 fleetId, uint8 stance, bytes32 target) external;
}
