// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

import { EResource } from "src/Types.sol";

/**
 * @title IMarketplaceSystem
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IMarketplaceSystem {
  function toggleMarketplaceLock() external;

  function addLiquidity(EResource resourceA, EResource resourceB, uint256 liquidityA, uint256 liquidityB) external;

  function removeLiquidity(EResource resourceA, EResource resourceB, uint256 liquidityA, uint256 liquidityB) external;

  function swap(bytes32 marketEntity, EResource[] memory path, uint256 amountIn, uint256 amountOutMin) external;
}
