// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IS_ClaimSystem
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IS_ClaimSystem {
  function claimUnits(bytes32 spaceRockEntity) external;

  function claimResources(bytes32 spaceRockEntity) external;
}
