// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IS_FleetResetIfNoUnitsLeftSystem
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IS_FleetResetIfNoUnitsLeftSystem {
  function resetFleetIfNoUnitsLeft(bytes32 fleetId) external;
}
