// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IS_InitializeSpaceRockOwnershipSystem
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IS_InitializeSpaceRockOwnershipSystem {
  function initializeSpaceRockOwnership(bytes32 spaceRock, bytes32 owner) external;
}
