// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IS_ProductionRateSystem
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IS_ProductionRateSystem {
  function upgradeProductionRate(bytes32 buildingEntity, uint256 level) external;

  function toggleProductionRate(bytes32 buildingEntity) external;

  function clearProductionRate(bytes32 buildingEntity) external;
}
