// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

import { PositionData } from "codegen/index.sol";

/**
 * @title IToggleBuildingSystem
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IToggleBuildingSystem {
  function toggleBuilding(PositionData memory coord) external returns (bool isActive);
}
