// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

import { ResourceId } from "@latticexyz/store/src/ResourceId.sol";

/**
 * @title IDelegationSystem
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IDelegationSystem {
  function unregisterDelegation(address authorizedAddress) external;

  function switchDelegation(
    address oldAuthorizedAddress,
    address newAuthorizedAddress,
    ResourceId delegationControlId,
    bytes memory initCallData
  ) external;
}
