// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IFleetLandSystem
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IFleetLandSystem {
  function landFleet(bytes32 fleetId, bytes32 spaceRock) external;
}
