// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IS_FleetResolvePirateAsteroidSystem
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IS_FleetResolvePirateAsteroidSystem {
  function resolvePirateAsteroid(bytes32 playerEntity, bytes32 pirateAsteroid) external;
}
