// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IS_RewardsSystem
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IS_RewardsSystem {
  function receiveRewards(bytes32 playerEntity, bytes32 spaceRockEntity, bytes32 objectivePrototype) external;
}
