// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IS_SpendResourcesSystem
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IS_SpendResourcesSystem {
  function spendBuildingRequiredResources(bytes32 buildingEntity, uint256 level) external;

  function spendUpgradeResources(bytes32 spaceRockEntity, bytes32 upgradePrototype, uint256 level) external;

  function toggleBuildingUtility(bytes32 buildingEntity) external;

  function clearUtilityUsage(bytes32 buildingEntity) external;
}
