// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IS_StorageSystem
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IS_StorageSystem {
  function increaseMaxStorage(bytes32 buildingEntity, uint256 level) external;

  function clearMaxStorageIncrease(bytes32 buildingEntity) external;

  function toggleMaxStorage(bytes32 buildingEntity) external;
}
