// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

import { EUnit } from "src/Types.sol";

/**
 * @title IUpgradeUnitSystem
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IUpgradeUnitSystem {
  function upgradeUnit(bytes32 spaceRockEntity, EUnit unit) external;
}
